### ISSUE TITLE
Some improvements: embed styles without using additional custom element, possible property factory

### ISSUE THREAD

**Issue by smalluban** [yochannah/biojs-webcomponent-prototype#3]
First of all, it is great to see the first public web component implementation using hybrids library 🎊.

https://github.com/yochannah/biojs-webcomponent-prototype/blob/e386bfd37abc83b0b771e6b8ffccaff85db438d2/src/index.js#L51

For now, the library does not have a snippet for including external style content (I am considering this). However, you don't have to create an additional element to pass styles into your custom element.

First of all, I can see that your custom element does not use shadowRoot, so styles should not be inside of the custom element at all (they will be processed by the document many times if a user would attach more than one your custom element in DOM).

Even though, if you want to do this, try using nested template feature in your main component:

```javascript
const styleTemplate = html([`<style>${styles}</style`]);

const BiojsComponentInteractionGraph = {
  ...,
  render: (host) => `
    <div>
      ${styleTemplate}
    </div>
  `,
```

The second thing, which I recommend is about your connection to external service. Instead of putting it inside of the render method, you can create a separate property or even property descriptor. If your code only requires access to the host, it is already there. If you need a nested div, you could create it manually, as your render method is called only once. It is overused here for sure.

It could look like this:

```javascript
function connectCymine(options) {
  return {
    get: (host, v) => v, // required to be recognized as property descriptor,
    connect: (host, key) => {
      host.appendChild(document.createElement('div'));  // if it is required in your case
      host[key] = Cymine({
        ...options,
        parentElem: host,
      });
  };
}

const BiojsComponentInteractionGraph = {
  cymine: connectCymine({ ... }),
  // your styles should be applied globaly to the document once, so render is not required
};
```

**Comment by yochannah** [comment]
@smalluban Thanks for the advice! Hybrids is a nice library, and it's not every day a developer gets code review directly from a library developer! 😊  I've made some tweaks, based on your suggestions - does that look saner to you?

**Comment by smalluban** [comment]
It should be `set`, not `get` method of course. My mistake. Get then is not required. However, what I can see you try to use attributes to setup your connection with `Cymine`. Your component, for now, use those attributes only once. If you want to allow users to pass options, it is a better idea to create properties for that (they fallbacks to attribute):

```javascript
const stylesTemplate = html([`<style>${styles}</style`]);

export const BiojsComponentInteractionGraph = {
  intermineService: '',
  searchTerm: '',
  searchOrganism: '',
  searchClass: '',
  cymine: {
    get: ({ intermineService, searchTerm, searchOrganism, searchClass }) => (host, target) => {
      const lastContainer = target.nextSibling;
      if (lastContainer) {
        lastContainer.parentElement.removeChild(lastContainer);
      }

      const nextContainer = document.createElement('div');
      target.parentElement.appendChild(nextContainer);

      Cymine({
        service: {
          root: intermineService,
        },
        queryOn: {
          value: searchTerm,
          extraValue: searchOrganism,
        },
        nodeType: searchClass,
        compact: true,
        parentElem: nextContainer,
      });
    },
  },
  render: ({ cymine }) => html`
    <div>${cymine}</div>
    ${stylesTemplate}
  `,
};
```
I am not familiar with `Cymine` library, but with that approach, every time when a user changes options, it will replace cymine instance. However, it will only change it when it is required. 

The other change here is with shadowRoot. I think you should use it and pass styles inside of it. This is one of the golden standard of web components, to not leak styles out of the web component.

`cymine` property is nested template here - you can read more about it [here](https://hybrids.js.org/template-engine/nested-templates). You can pass a function as a value in the template.

I did not test my solution, so check it out before commiting :)

**Comment by yochannah** [comment]
@smalluban Thanks. Should the intermineService, searchTerm, searchOrganism, searchClass properties automatically pick up values from the HTML attributes? Right now when I run this they end up as the same as they were initialised - an empty string `''`

**Comment by smalluban** [comment]
Empty strings are defaults. Property factory callbacks to attribute, but using dash notation (attributes are case insensitive). If you have `searchTerm` property, you have to use `search-term` attribute.
